auction:
  bid:
    intervalInSeconds: 3
    # Indicates how often could a player bid for one lot
  charge:
    chargePercentPerBid: 1
    # From 0 to 100
    minimumChargePerBid: 1
  useAsBlacklist: false
  # Change to true will use the following list as blacklist
  # You probably need a 'DEFAULT' item AT THE END OF THE LIST if you're using blacklist mode
  # A 'DEFAULT' item is an OPTIONAL special item that acts like a wildcard
  # Normally, a 'DEFAULT' item is put AT THE END OF THE LIST because the plugin find matching items orderly
  # A 'DEFAULT' item could be used in non-blacklist mode too, representing those items that don't have specific settings
  # To specify a 'DEFAULT' item, just set an item's ID to DEFAULT
  auctionableItems:
    - item: '4'
      startingPrice: 0.98
      minimumIncrement: 0.01
      # The minimum price increment for per bid
      preserveTimeInSeconds: 600
      # The time for which the item should be in the showcase before bidding for this item is started
      auctionDurationInSeconds: 300
      # The time in which the item should be sold after bidding for this item has started
    - item: DEFAULT
      startingPrice: 1.00
      minimumIncrement: 0.05
      preserveTimeInSeconds: 600
      auctionDurationInSeconds: 300
      
vault:
  capacity:
    defaultCapacity: 9
    # Max capacity: 54
    permissionControl: true
    # Whether to allow players' permission to override the capacity setting
    # Permission example: WowSuchCleaner.vault.capacity.18
    # Note: Max capacity still applies.
      
cleaning:
  active:
  # Active cleaning means cleaning by this plugin
    enabled: false
    # Whether to enable active cleaning
    auction: true
    # Whether to enable auction function for items cleaned by active cleaning
    autoMerge: false
    # Whether to merge same items into one item automatically
    intervalInSeconds: 600
    # The interval in seconds of active cleaning
    generousDelayInSeconds: 0
    # Items will not be removed until they've lived for ___ second(s).
    preservedItems:
    # These items are preserved from active cleaning
      - '2'
    notify:
    # Notify players when ___ seconds are left until active cleaning
      - 300
      - 60
      - 30
      - 10
  passive:
  # passive cleaning means cleaning by vanilla Minecraft
    auction: true
    # Whether to enable auction function for items cleaned by passive cleaning
    
locale: en_UK
# Locale files included by default: en_UK, zh_CN, de_DE